package com.ibm;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class OsversionTest {

    public static void main(String[] args) {

        List<InstallAgentPPPCInfo> pppcPayloadList = new ArrayList<>();
        InstallAgentPPPCInfo info1 = new InstallAgentPPPCInfo("10.15", "10.15 OS VERSION");
        InstallAgentPPPCInfo info2 = new InstallAgentPPPCInfo("11.0", "11.0 OS VERSION");
        InstallAgentPPPCInfo info3 = new InstallAgentPPPCInfo("12.0", "PHBsaXN0IHZlcnNpb249IjEuMCI+CjxkaWN0PgoJPGtleT5QYXlsb2FkQ29udGVudDwva2V5PgoJPGFycmF5PgoJCTxkaWN0PgoJCQk8a2V5PlBheWxvYWREZXNjcmlwdGlvbjwva2V5PgoJCQk8c3RyaW5nPk1hYVMgRXhlY3V0YWJsZXM8L3N0cmluZz4KCQkJPGtleT5QYXlsb2FkRGlzcGxheU5hbWU8L2tleT4KCQkJPHN0cmluZz5NYWFTIEV4ZWN1dGFibGVzPC9zdHJpbmc+CgkJCTxrZXk+UGF5bG9hZElkZW50aWZpZXI8L2tleT4KCQkJPHN0cmluZz5BMzFDQjFCOC0wNDczLTQxNzItODBENS0zMUYwQzQ3RTMyREY8L3N0cmluZz4KCQkJPGtleT5QYXlsb2FkT3JnYW5pemF0aW9uPC9rZXk+CgkJCTxzdHJpbmc+QWNoaWV2ZXJzPC9zdHJpbmc+CgkJCTxrZXk+UGF5bG9hZFR5cGU8L2tleT4KCQkJPHN0cmluZz5jb20uYXBwbGUuVENDLmNvbmZpZ3VyYXRpb24tcHJvZmlsZS1wb2xpY3k8L3N0cmluZz4KCQkJPGtleT5QYXlsb2FkVVVJRDwva2V5PgoJCQk8c3RyaW5nPkVDQUNCMEExLTUzQzUtNEMzRS04NUVFLUI1MTA0QjNFMzhGMjwvc3RyaW5nPgoJCQk8a2V5PlBheWxvYWRWZXJzaW9uPC9rZXk+CgkJCTxpbnRlZ2VyPjE8L2ludGVnZXI+CgkJCTxrZXk+U2VydmljZXM8L2tleT4KCQkJPGRpY3Q+CgkJCQk8a2V5PlN5c3RlbVBvbGljeUFsbEZpbGVzPC9rZXk+CgkJCQk8YXJyYXk+CgkJCQkJPGRpY3Q+CgkJCQkJCTxrZXk+QXV0aG9yaXphdGlvbjwva2V5PgoJCQkJCQk8c3RyaW5nPkFsbG93PC9zdHJpbmc+CgkJCQkJCTxrZXk+Q29kZVJlcXVpcmVtZW50PC9rZXk+CgkJCQkJCTxzdHJpbmc+aWRlbnRpZmllciAiY29tLmZpYmVybGluay5tYWFzMzYwLmFwcENhdGFsb2ciIGFuZCBhbmNob3IgYXBwbGUgZ2VuZXJpYyBhbmQgY2VydGlmaWNhdGUgMVtmaWVsZC4xLjIuODQwLjExMzYzNS4xMDAuNi4yLjZdIC8qIGV4aXN0cyAqLyBhbmQgY2VydGlmaWNhdGUgbGVhZltmaWVsZC4xLjIuODQwLjExMzYzNS4xMDAuNi4xLjEzXSAvKiBleGlzdHMgKi8gYW5kIGNlcnRpZmljYXRlIGxlYWZbc3ViamVjdC5PVV0gPSAiNzRQQjg4SEYyQiI8L3N0cmluZz4KCQkJCQkJPGtleT5Db21tZW50PC9rZXk+CgkJCQkJCTxzdHJpbmc+PC9zdHJpbmc+CgkJCQkJCTxrZXk+SWRlbnRpZmllcjwva2V5PgoJCQkJCQk8c3RyaW5nPmNvbS5maWJlcmxpbmsubWFhczM2MC5hcHBDYXRhbG9nPC9zdHJpbmc+CgkJCQkJCTxrZXk+SWRlbnRpZmllclR5cGU8L2tleT4KCQkJCQkJPHN0cmluZz5idW5kbGVJRDwvc3RyaW5nPgoJCQkJCTwvZGljdD4KCQkJCQk8ZGljdD4KCQkJCQkJPGtleT5BdXRob3JpemF0aW9uPC9rZXk+CgkJCQkJCTxzdHJpbmc+QWxsb3c8L3N0cmluZz4KCQkJCQkJPGtleT5Db2RlUmVxdWlyZW1lbnQ8L2tleT4KCQkJCQkJPHN0cmluZz5pZGVudGlmaWVyICJjb20uZmliZXJsaW5rLm1hYXMzNjAuZGlhZ25vc3RpY3Rvb2wiIGFuZCBhbmNob3IgYXBwbGUgZ2VuZXJpYyBhbmQgY2VydGlmaWNhdGUgMVtmaWVsZC4xLjIuODQwLjExMzYzNS4xMDAuNi4yLjZdIC8qIGV4aXN0cyAqLyBhbmQgY2VydGlmaWNhdGUgbGVhZltmaWVsZC4xLjIuODQwLjExMzYzNS4xMDAuNi4xLjEzXSAvKiBleGlzdHMgKi8gYW5kIGNlcnRpZmljYXRlIGxlYWZbc3ViamVjdC5PVV0gPSAiNzRQQjg4SEYyQiI8L3N0cmluZz4KCQkJCQkJPGtleT5Db21tZW50PC9rZXk+CgkJCQkJCTxzdHJpbmc+PC9zdHJpbmc+CgkJCQkJCTxrZXk+SWRlbnRpZmllcjwva2V5PgoJCQkJCQk8c3RyaW5nPmNvbS5maWJlcmxpbmsubWFhczM2MC5kaWFnbm9zdGljdG9vbDwvc3RyaW5nPgoJCQkJCQk8a2V5PklkZW50aWZpZXJUeXBlPC9rZXk+CgkJCQkJCTxzdHJpbmc+YnVuZGxlSUQ8L3N0cmluZz4KCQkJCQk8L2RpY3Q+CgkJCQkJPGRpY3Q+CgkJCQkJCTxrZXk+QXV0aG9yaXphdGlvbjwva2V5PgoJCQkJCQk8c3RyaW5nPkFsbG93PC9zdHJpbmc+CgkJCQkJCTxrZXk+Q29kZVJlcXVpcmVtZW50PC9rZXk+CgkJCQkJCTxzdHJpbmc+aWRlbnRpZmllciAiY29tLmZpYmVybGluay5tYWFzMzYwLkxhdW5jaC1NYWFTMzYwIiBhbmQgYW5jaG9yIGFwcGxlIGdlbmVyaWMgYW5kIGNlcnRpZmljYXRlIDFbZmllbGQuMS4yLjg0MC4xMTM2MzUuMTAwLjYuMi42XSAvKiBleGlzdHMgKi8gYW5kIGNlcnRpZmljYXRlIGxlYWZbZmllbGQuMS4yLjg0MC4xMTM2MzUuMTAwLjYuMS4xM10gLyogZXhpc3RzICovIGFuZCBjZXJ0aWZpY2F0ZSBsZWFmW3N1YmplY3QuT1VdID0gIjc0UEI4OEhGMkIiPC9zdHJpbmc+CgkJCQkJCTxrZXk+Q29tbWVudDwva2V5PgoJCQkJCQk8c3RyaW5nPjwvc3RyaW5nPgoJCQkJCQk8a2V5PklkZW50aWZpZXI8L2tleT4KCQkJCQkJPHN0cmluZz5jb20uZmliZXJsaW5rLm1hYXMzNjAuTGF1bmNoLU1hYVMzNjA8L3N0cmluZz4KCQkJCQkJPGtleT5JZGVudGlmaWVyVHlwZTwva2V5PgoJCQkJCQk8c3RyaW5nPmJ1bmRsZUlEPC9zdHJpbmc+CgkJCQkJPC9kaWN0PgoJCQkJCTxkaWN0PgoJCQkJCQk8a2V5PkF1dGhvcml6YXRpb248L2tleT4KCQkJCQkJPHN0cmluZz5BbGxvdzwvc3RyaW5nPgoJCQkJCQk8a2V5PkNvZGVSZXF1aXJlbWVudDwva2V5PgoJCQkJCQk8c3RyaW5nPmlkZW50aWZpZXIgImNvbS5maWJlcmxpbmsubWFhczM2MC5tZXNzYWdlc2Zvcm1hYyIgYW5kIGFuY2hvciBhcHBsZSBnZW5lcmljIGFuZCBjZXJ0aWZpY2F0ZSAxW2ZpZWxkLjEuMi44NDAuMTEzNjM1LjEwMC42LjIuNl0gLyogZXhpc3RzICovIGFuZCBjZXJ0aWZpY2F0ZSBsZWFmW2ZpZWxkLjEuMi44NDAuMTEzNjM1LjEwMC42LjEuMTNdIC8qIGV4aXN0cyAqLyBhbmQgY2VydGlmaWNhdGUgbGVhZltzdWJqZWN0Lk9VXSA9ICI3NFBCODhIRjJCIjwvc3RyaW5nPgoJCQkJCQk8a2V5PkNvbW1lbnQ8L2tleT4KCQkJCQkJPHN0cmluZz48L3N0cmluZz4KCQkJCQkJPGtleT5JZGVudGlmaWVyPC9rZXk+CgkJCQkJCTxzdHJpbmc+Y29tLmZpYmVybGluay5tYWFzMzYwLm1lc3NhZ2VzZm9ybWFjPC9zdHJpbmc+CgkJCQkJCTxrZXk+SWRlbnRpZmllclR5cGU8L2tleT4KCQkJCQkJPHN0cmluZz5idW5kbGVJRDwvc3RyaW5nPgoJCQkJCTwvZGljdD4KCQkJCQk8ZGljdD4KCQkJCQkJPGtleT5BdXRob3JpemF0aW9uPC9rZXk+CgkJCQkJCTxzdHJpbmc+QWxsb3c8L3N0cmluZz4KCQkJCQkJPGtleT5Db2RlUmVxdWlyZW1lbnQ8L2tleT4KCQkJCQkJPHN0cmluZz5pZGVudGlmaWVyICJjb20uRmliZXJsaW5rLk1hYVMzNjAuRmlsZVN5bmNBZ2VudCIgYW5kIGFuY2hvciBhcHBsZSBnZW5lcmljIGFuZCBjZXJ0aWZpY2F0ZSAxW2ZpZWxkLjEuMi44NDAuMTEzNjM1LjEwMC42LjIuNl0gLyogZXhpc3RzICovIGFuZCBjZXJ0aWZpY2F0ZSBsZWFmW2ZpZWxkLjEuMi44NDAuMTEzNjM1LjEwMC42LjEuMTNdIC8qIGV4aXN0cyAqLyBhbmQgY2VydGlmaWNhdGUgbGVhZltzdWJqZWN0Lk9VXSA9ICI3NFBCODhIRjJCIjwvc3RyaW5nPgoJCQkJCQk8a2V5PkNvbW1lbnQ8L2tleT4KCQkJCQkJPHN0cmluZz48L3N0cmluZz4KCQkJCQkJPGtleT5JZGVudGlmaWVyPC9rZXk+CgkJCQkJCTxzdHJpbmc+Y29tLkZpYmVybGluay5NYWFTMzYwLkZpbGVTeW5jQWdlbnQ8L3N0cmluZz4KCQkJCQkJPGtleT5JZGVudGlmaWVyVHlwZTwva2V5PgoJCQkJCQk8c3RyaW5nPmJ1bmRsZUlEPC9zdHJpbmc+CgkJCQkJPC9kaWN0PgoJCQkJCTxkaWN0PgoJCQkJCQk8a2V5PkF1dGhvcml6YXRpb248L2tleT4KCQkJCQkJPHN0cmluZz5BbGxvdzwvc3RyaW5nPgoJCQkJCQk8a2V5PkNvZGVSZXF1aXJlbWVudDwva2V5PgoJCQkJCQk8c3RyaW5nPmlkZW50aWZpZXIgImNvbS5maWJlcmxpbmsubWFhczM2MC5zZXJ2aWNlZGFlbW9uIiBhbmQgYW5jaG9yIGFwcGxlIGdlbmVyaWMgYW5kIGNlcnRpZmljYXRlIDFbZmllbGQuMS4yLjg0MC4xMTM2MzUuMTAwLjYuMi42XSAvKiBleGlzdHMgKi8gYW5kIGNlcnRpZmljYXRlIGxlYWZbZmllbGQuMS4yLjg0MC4xMTM2MzUuMTAwLjYuMS4xM10gLyogZXhpc3RzICovIGFuZCBjZXJ0aWZpY2F0ZSBsZWFmW3N1YmplY3QuT1VdID0gIjc0UEI4OEhGMkIiPC9zdHJpbmc+CgkJCQkJCTxrZXk+Q29tbWVudDwva2V5PgoJCQkJCQk8c3RyaW5nPjwvc3RyaW5nPgoJCQkJCQk8a2V5PklkZW50aWZpZXI8L2tleT4KCQkJCQkJPHN0cmluZz5jb20uZmliZXJsaW5rLm1hYXMzNjAuc2VydmljZWRhZW1vbjwvc3RyaW5nPgoJCQkJCQk8a2V5PklkZW50aWZpZXJUeXBlPC9rZXk+CgkJCQkJCTxzdHJpbmc+YnVuZGxlSUQ8L3N0cmluZz4KCQkJCQk8L2RpY3Q+CgkJCQkJPGRpY3Q+CgkJCQkJCTxrZXk+QXV0aG9yaXphdGlvbjwva2V5PgoJCQkJCQk8c3RyaW5nPkFsbG93PC9zdHJpbmc+CgkJCQkJCTxrZXk+Q29kZVJlcXVpcmVtZW50PC9rZXk+CgkJCQkJCTxzdHJpbmc+aWRlbnRpZmllciAiY29tLmZpYmVybGluay5tYWFzMzYwLnVwZ3JhZGVkYWVtb24iIGFuZCBhbmNob3IgYXBwbGUgZ2VuZXJpYyBhbmQgY2VydGlmaWNhdGUgMVtmaWVsZC4xLjIuODQwLjExMzYzNS4xMDAuNi4yLjZdIC8qIGV4aXN0cyAqLyBhbmQgY2VydGlmaWNhdGUgbGVhZltmaWVsZC4xLjIuODQwLjExMzYzNS4xMDAuNi4xLjEzXSAvKiBleGlzdHMgKi8gYW5kIGNlcnRpZmljYXRlIGxlYWZbc3ViamVjdC5PVV0gPSAiNzRQQjg4SEYyQiI8L3N0cmluZz4KCQkJCQkJPGtleT5Db21tZW50PC9rZXk+CgkJCQkJCTxzdHJpbmc+PC9zdHJpbmc+CgkJCQkJCTxrZXk+SWRlbnRpZmllcjwva2V5PgoJCQkJCQk8c3RyaW5nPmNvbS5maWJlcmxpbmsubWFhczM2MC51cGdyYWRlZGFlbW9uPC9zdHJpbmc+CgkJCQkJCTxrZXk+SWRlbnRpZmllclR5cGU8L2tleT4KCQkJCQkJPHN0cmluZz5idW5kbGVJRDwvc3RyaW5nPgoJCQkJCTwvZGljdD4KCQkJCQk8ZGljdD4KCQkJCQkJPGtleT5BdXRob3JpemF0aW9uPC9rZXk+CgkJCQkJCTxzdHJpbmc+QWxsb3c8L3N0cmluZz4KCQkJCQkJPGtleT5Db2RlUmVxdWlyZW1lbnQ8L2tleT4KCQkJCQkJPHN0cmluZz5pZGVudGlmaWVyICJjb20uZmliZXJsaW5rLm1hYXMzNjAudmlzaWJpbGl0eSIgYW5kIGFuY2hvciBhcHBsZSBnZW5lcmljIGFuZCBjZXJ0aWZpY2F0ZSAxW2ZpZWxkLjEuMi44NDAuMTEzNjM1LjEwMC42LjIuNl0gLyogZXhpc3RzICovIGFuZCBjZXJ0aWZpY2F0ZSBsZWFmW2ZpZWxkLjEuMi44NDAuMTEzNjM1LjEwMC42LjEuMTNdIC8qIGV4aXN0cyAqLyBhbmQgY2VydGlmaWNhdGUgbGVhZltzdWJqZWN0Lk9VXSA9ICI3NFBCODhIRjJCIjwvc3RyaW5nPgoJCQkJCQk8a2V5PkNvbW1lbnQ8L2tleT4KCQkJCQkJPHN0cmluZz48L3N0cmluZz4KCQkJCQkJPGtleT5JZGVudGlmaWVyPC9rZXk+CgkJCQkJCTxzdHJpbmc+Y29tLmZpYmVybGluay5tYWFzMzYwLnZpc2liaWxpdHk8L3N0cmluZz4KCQkJCQkJPGtleT5JZGVudGlmaWVyVHlwZTwva2V5PgoJCQkJCQk8c3RyaW5nPmJ1bmRsZUlEPC9zdHJpbmc+CgkJCQkJPC9kaWN0PgoJCQkJCTxkaWN0PgoJCQkJCQk8a2V5PkF1dGhvcml6YXRpb248L2tleT4KCQkJCQkJPHN0cmluZz5BbGxvdzwvc3RyaW5nPgoJCQkJCQk8a2V5PkNvZGVSZXF1aXJlbWVudDwva2V5PgoJCQkJCQk8c3RyaW5nPmlkZW50aWZpZXIgImNvbS5maWJlcmxpbmsubWFhczM2MC51dGlsaXR5Rm9yQXBwQ2F0YWxvZyIgYW5kIGFuY2hvciBhcHBsZSBnZW5lcmljIGFuZCBjZXJ0aWZpY2F0ZSAxW2ZpZWxkLjEuMi44NDAuMTEzNjM1LjEwMC42LjIuNl0gLyogZXhpc3RzICovIGFuZCBjZXJ0aWZpY2F0ZSBsZWFmW2ZpZWxkLjEuMi44NDAuMTEzNjM1LjEwMC42LjEuMTNdIC8qIGV4aXN0cyAqLyBhbmQgY2VydGlmaWNhdGUgbGVhZltzdWJqZWN0Lk9VXSA9ICI3NFBCODhIRjJCIjwvc3RyaW5nPgoJCQkJCQk8a2V5PkNvbW1lbnQ8L2tleT4KCQkJCQkJPHN0cmluZz48L3N0cmluZz4KCQkJCQkJPGtleT5JZGVudGlmaWVyPC9rZXk+CgkJCQkJCTxzdHJpbmc+L0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9NYWFTMzYwL0V4ZWN1dGFibGVzL01hYVMzNjBBcHBDYXRhbG9nVXRpbGl0eTwvc3RyaW5nPgoJCQkJCQk8a2V5PklkZW50aWZpZXJUeXBlPC9rZXk+CgkJCQkJCTxzdHJpbmc+cGF0aDwvc3RyaW5nPgoJCQkJCTwvZGljdD4KCQkJCTwvYXJyYXk+CgkJCTwvZGljdD4KCQk8L2RpY3Q+Cgk8L2FycmF5PgoJPGtleT5QYXlsb2FkRGVzY3JpcHRpb248L2tleT4KCTxzdHJpbmc+TWFhUyBFeGVjdXRhYmxlczwvc3RyaW5nPgoJPGtleT5QYXlsb2FkRGlzcGxheU5hbWU8L2tleT4KCTxzdHJpbmc+TWFhUyBFeGVjdXRhYmxlczwvc3RyaW5nPgoJPGtleT5QYXlsb2FkSWRlbnRpZmllcjwva2V5PgoJPHN0cmluZz5BMzFDQjFCOC0wNDczLTQxNzItODBENS0zMUYwQzQ3RTMyREY8L3N0cmluZz4KCTxrZXk+UGF5bG9hZE9yZ2FuaXphdGlvbjwva2V5PgoJPHN0cmluZz5BY2hpZXZlcnM8L3N0cmluZz4KCTxrZXk+UGF5bG9hZFNjb3BlPC9rZXk+Cgk8c3RyaW5nPlN5c3RlbTwvc3RyaW5nPgoJPGtleT5QYXlsb2FkVHlwZTwva2V5PgoJPHN0cmluZz5Db25maWd1cmF0aW9uPC9zdHJpbmc+Cgk8a2V5PlBheWxvYWRVVUlEPC9rZXk+Cgk8c3RyaW5nPjVGRUI0NEE3LUFBQjMtNEU0Ri1CRTUwLTlGMEI3NDRGNTNCRjwvc3RyaW5nPgoJPGtleT5QYXlsb2FkVmVyc2lvbjwva2V5PgoJPGludGVnZXI+MTwvaW50ZWdlcj4KPC9kaWN0Pgo8L3BsaXN0Pg==");
        InstallAgentPPPCInfo info4 = new InstallAgentPPPCInfo("11.1", "11.1 OS VERSION");
        InstallAgentPPPCInfo info5 = new InstallAgentPPPCInfo("10.1", "10.1 OS VERSION");
        pppcPayloadList.add(info1);
        pppcPayloadList.add(info2);
        pppcPayloadList.add(info3);
        pppcPayloadList.add(info4);
        pppcPayloadList.add(info5);

        Map<String, String> payloadData = new HashMap<>();

        for (InstallAgentPPPCInfo info : pppcPayloadList) {
            payloadData.put(info.getOsVersion(), info.getPayload());
        }


        System.out.println(getLongArrayList(payloadData.keySet()));
    }

    private static List<Float> getLongArrayList(Set<String> keySet) {
        List<Float> longArrayList = new ArrayList<>();
        try {
            for (String macversion : keySet) {
                Float macVersionLongValue;
                String versionFields[] = macversion.split("\\.");
                if (versionFields.length >= 2) {
                    String val = versionFields[0] + "." + versionFields[1];
                    System.out.println("val: " + val);
                    macVersionLongValue = Float.valueOf(val);
                } else {
                    macVersionLongValue = Float.valueOf(versionFields[0]);
                }
                longArrayList.add(macVersionLongValue);
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
        return longArrayList;
    }
}
